name: '[GDRIVE] Download'
on:
  workflow_dispatch:
    inputs:
      PATH_FROM:
          description: 'Folder to export'
          default: './Fotos/' 
          type: string
      PATH_TO:
          description: 'Folder to export'
          default: './' 
          type: string
jobs:
  download-gdriver:
    runs-on: ubuntu-latest
    steps:
      - name: Download from Google Drive
        uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          download-from: ${{inputs.PATH_FROM}}
          download-to:  ${{inputs.PATH_TO}}
      
          # For those who set up Google Drive API client ID and secret themselves
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
