name: Download from Google Drive

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Download files from Google Drive
        uses: satackey/action-google-drive@v14
        with:
        skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
        download-from: ./Fotos/
        download-to: ./

        # For those who set up Google Drive API client ID and secret themselves
        google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
        google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
